export const PATH = {
  HOME: '/',
  SIGN_IN: '/signin',
  SIGN_UP: '/signup',
  OAUTH_KAKAO: '/oauth/kakao',
  CALENDAR: '/calendar',
  CALENDAR_WRITE: '/calendar/write',
  CALENDAR_EDIT: '/calendar/edit',
  TIMELINE: '/timeline',
  REPORT: '/report',
  REPORT_QUESTION: '/report/question',
  REPORT_ANSWER: '/report/answer',
  REPORT_DETAIL: '/report/answer/:id',
  SETTING: '/setting',
  SETTING_MODIFY_NAME: '/setting/modifyName',
  SETTING_MODIFY_PASSWORD: '/setting/modifyPassword',
  SETTING_PRIVACY: '/setting/privacy',
  ERROR: '*',
};
