export const PATH = {
  HOME: '/',
  SIGN_IN: '/signin',
  SIGN_UP: '/signup',
  OAUTH_KAKAO: '/oauth/kakao',
  CALENDAR: '/calendar',
  WRITE: '/calendar/write',
  EDIT: '/calendar/edit',
  TIMELINE: '/timeline',
  REPORT: '/report',
  QUESTION: '/report/question',
  RESULT: '/report/result/:id',
  REPORTLIST: '/report/report_list',
  REPORTITEM: '/report/report_list/:id',
  SETTING: '/setting',
};
